site_name: InterfaceSmith Documentation
theme:
  name: material
nav:
  - Home: index.md
  - User Guide:
    - Getting Started: user-guide/getting-started.md
    - Data Preparation: user-guide/data-preparation.md
  - Developer Guide:
    - Architecture: dev-guide/architecture.md
    - Core Logic: dev-guide/core-logic.md
