site_name: InterfaceSmith Documentation
theme:
  name: material
nav:
  - Home: index.md
  - User Guide:
    - Getting Started: user-guide/getting-started.md
    - Input Data Guide: user-guide/data-preparation.md
    - Creating UI elements : user-guide/element-creation.md
    - Modifying UI elements : user-guide/element-modification.md
    - Implementing custom logic : user-guide/custom-functionality.md
  - Developer Guide:
    - Getting Started: dev-guide/getting-started.md
    - Architecture: dev-guide/architecture.md
    - Core Logic: dev-guide/core-logic.md
    - Editor UI: dev-guide/editor.md